// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_home.cpp"
#include "EWIEGA46WW/moc_linear_reg.cpp"
#include "EWIEGA46WW/moc_naive.cpp"
#include "EWIEGA46WW/moc_tf_idf.cpp"
#include "EWIEGA46WW/moc_widget.cpp"
